[package]
name = "web-common"
version = "0.1.0"
authors = ["manpat <pat@patsown.com>"]

[dependencies]
common = { git = "https://github.com/manpat/common-rs.git", branch="cruft-resurrection" }
# common = { path = "../common" }

png = "0.10.0"
